eureka:         
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://192.168.1.11:8000/eureka/  
      defaultZone: http://10.0.0.10:8000/eureka/       
    healthcheck:
      enabled: true
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
logging: 
  level:   
    com.pro.common: DEBUG
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.hibernate: ERROR    
  file: common-service.log